### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by tzohpilotl** [dannharo/myWebPage#5]
Daniel, hello. Two are the things I loved about your page and the first one is that beautiful green you chose; the second one are those pretty social network icons at the bottom. Also the detail of adding some color to one of the sections to avoid plainliness is a neat move. Two things also pop to my eye: one, that your navbar always has the "About me" section active until you click other link; two, that you put a dot (.) in some of your headers and in others don't. Usually one doesn't put dots in headers. Nothing more for the moment, so have a good night!

**Comment by dannharo** [comment]
Thank you for your observations, I've corrected those issues.
